/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type TabType = 'home' | 'ask' | 'viva' | 'progress' | 'notes' | 'profile' | 'settings' | 'revision';

/**
 * User Profile & Account Data
 * Associated with the authenticated Firebase user
 */
export interface User {
  id: string; // Firebase Auth UID
  name: string;
  email: string;
  studyLevel: string; // e.g., "Undergraduate", "High School", "Medical Student"
  subjects: string[]; // e.g., ["Biology", "Chemistry"]
  bio: string;
  avatarUrl?: string;
  createdAt: Date;
}

/**
 * User Specific Preferences & Study Settings
 */
export interface UserSettings {
  userId: string;
  answerStyle: 'academic' | 'simple' | 'conversational';
  examOriented: boolean;
  responseType: 'detailed' | 'concise';
  allowExtraInfo: boolean;
  sourceVisibility: 'always' | 'collapsed' | 'hidden';
  theme: 'dark' | 'light';
  studyReminders: boolean;
  revisionReminders: boolean;
  vivaReminders: boolean;
}

/**
 * Source study materials uploaded by the user
 */
export interface StudyMaterial {
  id: string;
  userId: string; // Owner ID
  type: 'pdf' | 'text';
  name: string;
  content: string; // File contents representation or pasted text
  fileSize?: string;
  pageCount?: number;
  uploadedAt: Date;
}

/**
 * Represent chunks for document parsing/chunking ready for vector search embeddings
 */
export interface MaterialChunk {
  id: string;
  materialId: string;
  text: string;
  indexOrder: number;
  pageNumber?: number;
  vectorEmbeddingStatus: 'pending' | 'completed' | 'failed';
}

/**
 * Personal Study Notes derived from Ask Q&A
 */
export interface StudyNote {
  id: string;
  userId: string; // Owner ID
  title: string;
  summary: string;
  keyConcepts: string[];
  definitions: { term: string; definition: string }[];
  mechanisms: string[];
  examPoints: string[];
  memoryCues: string[];
  vivaQuestions: string[];
  sourceTitle: string;
  createdAt: Date;
  isFavorite: boolean;
}

export interface Source {
  title: string;
  page?: number;
  excerpt: string;
}

/**
 * Natural language questions asked by the user
 */
export interface Question {
  id: string;
  userId: string;
  text: string;
  timestamp: Date;
}

/**
 * Answers generated by the AI model based on materials or general knowledge
 */
export interface Answer {
  id: string;
  questionId: string;
  text: string;
  timestamp: Date;
  sources?: Source[];
  isExtraInfo?: boolean;
}

/**
 * Chat conversation logs (Combines user questions and AI answers for easy UI rendering)
 */
export interface Message {
  id: string;
  sender: 'user' | 'assistant' | 'system';
  text: string;
  timestamp: Date;
  sources?: Source[];
  isExtraInfo?: boolean;
}

/**
 * Study session tracks
 */
export interface StudySession {
  id: string;
  userId: string;
  startTime: Date;
  endTime?: Date;
  type: 'ask' | 'viva' | 'reading';
  activeTopic?: string;
}

export interface RevisionConcept {
  name: string;
  reason?: string;
  explanation?: string;
  why?: string;
  quickReminder?: string;
  priority?: 'high' | 'medium';
}

export interface RevisionPlan {
  concepts: RevisionConcept[];
}

export interface SmartRevisionSession {
  id: string;
  userId: string;
  materialId: string;
  materialTitle: string;
  duration: number;
  startTime: Date;
  plan?: RevisionPlan;
}
export interface VivaSession {
  id: string;
  userId: string;
  materialId?: string; // Optional material context
  startTime: Date;
  endTime?: Date;
  status: 'active' | 'completed';
  score?: number; // Calculated summary percentage accuracy
  topic: string;
}

/**
 * Individual answers/responses in a Viva Session
 */
export interface VivaResponse {
  id: string;
  sessionId: string;
  questionText: string;
  userResponseText: string;
  evaluationFeedback: string;
  accuracyScore: number; // e.g. 0 to 100 evaluation
  timestamp: Date;
}

/**
 * Aggregated analytics & progress maps for the user
 */
export interface UserProgress {
  id: string;
  userId: string;
  topicsStudiedCount: number;
  questionsAskedCount: number;
  notesCreatedCount: number;
  vivaSessionsCount: number;
  streakDays: number;
  lastStudyDate?: Date;
}

/**
 * High level concepts or focus topics tracked over time
 */
export interface FocusTopic {
  id: string;
  userId: string;
  name: string;
  strength: 'high' | 'medium' | 'low'; // Adaptive state
  lastStudiedAt: Date;
  status: 'mastered' | 'learning' | 'needs_review';
}

/**
 * Dynamic event logger for study analytics
 */
export interface StudyActivity {
  id: string;
  userId: string;
  type: 'ask' | 'viva' | 'upload' | 'note_created';
  description: string;
  timestamp: Date;
}
